name: mobil_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  fluttertoast: ^8.2.5
  image_picker: ^0.8.4+4
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  cupertino_icons: ^1.0.8

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    
flutter_launcher_icons:
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#235586"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  ios: true
  remove_alpha_ios: true
  android: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true